### ISSUE TITLE
Trail is very jagged

### ISSUE THREAD

**Issue by sgpthomas** [sgpthomas/trails#2]
Figure out a way to draw the trail so that it remains smooth

**Comment by iarbak** [comment]
The more recent versions deal with that. They add a few buffer pixels on either side of each sub-segment.

**Comment by iarbak** [comment]
On second thoughts, I see what you mean.
If we're to make a genuinely smooth curve, what immediately occurs to me is using drawArc. Or draw path using arcs.
You'd need to calculate sweep angle between each two points, which could be approximated in radians as diagonal distance between the two points (which would require calculating x^2 + y^2) divided by change in y. And even then you'd get a result that wouldn't be very accurate for larger angles (for 90 degrees, that would be 1.414 calculated vs 1.57 actual rad).
But this will probably require considerably more computation to draw, which might slow down time between frames, which might ruin the animation for longer trails.
As it is, I'm a little worried about jerky graphics on my phone.

**Comment by iarbak** [comment]
If you could consult your friend (or have any ideas yourself), we could draw the trail with a texture or style such that the jaggedness ends up looking good.
For example, one thing that can be done is making each segment a different color and width.

**Comment by iarbak** [comment]
resolved stylistically
